name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Init environment
        run: poetry install
      - name: Unit tests
        run: poetry run pytest tests
